"use client";

import React, { useState, useMemo } from 'react';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import { Line } from 'react-chartjs-2';
import InputSlider from '@/components/InputSlider';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

export default function SavingsVsDcaPage() {
  const [monthlyInvestment, setMonthlyInvestment] = useState(500);
  const [years, setYears] = useState(10);
  const [fdRate, setFdRate] = useState(4.5);
  const [dcaRate, setDcaRate] = useState(10);

  const calculateFutureValue = (monthly, rate, years) => {
    const months = years * 12;
    const monthlyRate = rate / 100 / 12;
    if (monthlyRate === 0) return monthly * months;
    return monthly * ((Math.pow(1 + monthlyRate, months) - 1) / monthlyRate) * (1 + monthlyRate);
  };

  const { fdTotal, dcaTotal, totalInvested, chartData } = useMemo(() => {
    const fd = calculateFutureValue(monthlyInvestment, fdRate, years);
    const dca = calculateFutureValue(monthlyInvestment, dcaRate, years);
    const invested = monthlyInvestment * years * 12;

    const labels = [];
    const fdData = [];
    const dcaData = [];

    for (let i = 0; i <= years; i++) {
      labels.push(`Year ${i}`);
      if (i === 0) {
        fdData.push(0);
        dcaData.push(0);
      } else {
        fdData.push(calculateFutureValue(monthlyInvestment, fdRate, i));
        dcaData.push(calculateFutureValue(monthlyInvestment, dcaRate, i));
      }
    }

    return {
      fdTotal: fd,
      dcaTotal: dca,
      totalInvested: invested,
      chartData: {
        labels,
        datasets: [
          {
            label: 'DCA Value',
            data: dcaData,
            borderColor: 'var(--color-accent)',
            backgroundColor: 'var(--color-accent)',
            borderWidth: 2,
            pointRadius: 0,
            pointHitRadius: 10,
            tension: 0.4,
          },
          {
            label: 'Savings Value',
            data: fdData,
            borderColor: '#C4993C',
            backgroundColor: '#C4993C',
            borderWidth: 2,
            pointRadius: 0,
            pointHitRadius: 10,
            tension: 0.4,
          },
        ],
      },
    };
  }, [monthlyInvestment, years, fdRate, dcaRate]);

  const extraWealth = dcaTotal - fdTotal;

  const formatCurrency = (value) =>
    new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      maximumFractionDigits: 0,
    }).format(value);

  const chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: 'top',
        labels: {
          color: '#8B95A5',
          usePointStyle: true,
          boxWidth: 8,
        },
      },
      tooltip: {
        mode: 'index',
        intersect: false,
        callbacks: {
          label: (context) => {
            let label = context.dataset.label || '';
            if (label) {
              label += ': ';
            }
            if (context.parsed.y !== null) {
              label += formatCurrency(context.parsed.y);
            }
            return label;
          },
        },
      },
    },
    scales: {
      x: {
        grid: {
          display: false,
        },
        ticks: {
          color: '#8B95A5',
          maxTicksLimit: 8,
        },
      },
      y: {
        grid: {
          color: 'rgba(139,149,165,0.1)',
        },
        ticks: {
          color: '#8B95A5',
          callback: (value) => {
            if (value >= 1000000) return `$${(value / 1000000).toFixed(1)}M`;
            if (value >= 1000) return `$${(value / 1000).toFixed(1)}K`;
            return `$${value}`;
          },
        },
      },
    },
    interaction: {
      mode: 'nearest',
      axis: 'x',
      intersect: false,
    },
  };

  return (
    <>
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="text-center mb-10">
        <h1 className="text-3xl md:text-4xl font-bold text-[var(--foreground)] mb-4">
          Savings vs DCA Calculator
        </h1>
        <p className="text-gray-500 dark:text-gray-400 max-w-2xl mx-auto">
          Compare the wealth generated by a traditional CD or High-Yield Savings Account versus Dollar Cost Averaging (DCA) into index funds over time.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Input Panel */}
        <div className="lg:col-span-5 space-y-6 glass-panel p-6 sm:p-8 rounded-2xl bg-[var(--background)]">
          <h2 className="text-xl font-bold text-[var(--foreground)] mb-6">Investment Details</h2>
          
          <InputSlider
            label="Monthly Investment"
            value={monthlyInvestment}
            min={100}
            max={10000}
            step={50}
            onChange={setMonthlyInvestment}
            prefix="$"
          />

          <InputSlider
            label="Investment Period"
            value={years}
            min={1}
            max={30}
            step={1}
            onChange={setYears}
            suffix=" Years"
          />

          <InputSlider
            label="Savings Interest Rate (APY)"
            value={fdRate}
            min={1}
            max={15}
            step={0.1}
            onChange={setFdRate}
            suffix="%"
          />

          <InputSlider
            label="DCA Expected Return (APY)"
            value={dcaRate}
            min={1}
            max={30}
            step={0.1}
            onChange={setDcaRate}
            suffix="%"
          />
        </div>

        {/* Results Panel */}
        <div className="lg:col-span-7 space-y-8">
          <div className="glass-panel p-6 sm:p-8 rounded-2xl bg-[var(--background)]">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-8">
              <div className="p-4 rounded-xl bg-[var(--background)] border border-[var(--panel-border)]">
                <p className="text-sm text-gray-500 dark:text-gray-400 mb-1">Total Invested</p>
                <p className="text-2xl font-bold text-[var(--color-accent)]">
                  {formatCurrency(totalInvested)}
                </p>
              </div>
              <div className="p-4 rounded-xl bg-[var(--color-accent)] text-white shadow-lg">
                <p className="text-sm text-white/80 mb-1">Extra Wealth via DCA</p>
                <p className="text-2xl font-bold text-white">
                  {formatCurrency(extraWealth)}
                </p>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-8">
              <div className="p-4 rounded-xl bg-[var(--background)] border border-[var(--panel-border)]">
                <p className="text-sm text-gray-500 dark:text-gray-400 mb-1 flex items-center gap-2">
                  <span className="w-3 h-3 rounded-full bg-[#C4993C]"></span>
                  Savings Total Value
                </p>
                <p className="text-2xl font-bold text-[var(--foreground)]">
                  {formatCurrency(fdTotal)}
                </p>
                <p className="text-sm text-[var(--color-returns)] mt-1">
                  +{formatCurrency(fdTotal - totalInvested)} gains
                </p>
              </div>
              <div className="p-4 rounded-xl bg-[var(--background)] border border-[var(--panel-border)]">
                <p className="text-sm text-gray-500 dark:text-gray-400 mb-1 flex items-center gap-2">
                  <span className="w-3 h-3 rounded-full bg-[var(--color-accent)]"></span>
                  DCA Total Value
                </p>
                <p className="text-2xl font-bold text-[var(--foreground)]">
                  {formatCurrency(dcaTotal)}
                </p>
                <p className="text-sm text-[var(--color-returns)] mt-1">
                  +{formatCurrency(dcaTotal - totalInvested)} gains
                </p>
              </div>
            </div>

            <div className="h-[300px] w-full">
              <Line data={chartData} options={chartOptions} />
            </div>
          </div>
        </div>
      </div>

      {/* SEO Educational Content Section */}
      <div className="mt-16 bg-[var(--panel-bg)] rounded-3xl p-8 shadow-sm border border-gray-100 w-full">
        <h2 className="text-2xl font-bold text-[var(--foreground)] mb-6">Why You Should Compare Savings vs DCA</h2>
        
        <div className="space-y-6 text-gray-600 dark:text-gray-400 leading-relaxed">
          <p>
            Leaving your money in a High-Yield Savings Account (HYSA) or Certificate of Deposit (CD) might feel safe, but it often carries a hidden risk: <strong>inflation drag</strong>. While your nominal balance grows by 4-5% APY, the cost of living (inflation) typically rises at 3% historically, and sometimes much higher. This means the <em>real</em> purchasing power of your cash barely grows.
          </p>

          <h3 className="text-xl font-semibold text-[var(--foreground)] mt-8 mb-4">What is Dollar Cost Averaging (DCA)?</h3>
          <p>
            Dollar Cost Averaging (DCA) is a strategy where you invest a fixed amount of money at regular intervals (e.g., every month), regardless of whether the stock market is up or down. By investing automatically into diversified vehicles like S&P 500 index funds or a 401(k), you buy more shares when prices are low and fewer shares when prices are high. 
          </p>

          <p>
            Historically, the US stock market has delivered an average annual return of roughly 10% before inflation. While it experiences short-term volatility, a long-term DCA strategy takes advantage of compound growth, significantly outpacing the returns of fixed-income savings accounts.
          </p>

          <h3 className="text-xl font-semibold text-[var(--foreground)] mt-8 mb-4">The Opportunity Cost of Cash</h3>
          <p>
            Use the calculator above to see the staggering difference between a 4% savings rate and a 10% index fund return over 20 years. That difference is the <strong>opportunity cost of holding cash</strong>. While everyone needs an emergency fund (usually 3 to 6 months of expenses) kept in a highly liquid and safe savings account, parking long-term retirement wealth in cash is statistically one of the most dangerous financial decisions you can make.
          </p>
          </div>
        </div>
      </div>

      {/* How to Use */}
      <div className="glass-panel p-6 mt-12 max-w-7xl mx-auto rounded-3xl">
        <h2 className="text-xl font-bold text-[var(--foreground)] mb-4 flex items-center gap-2">
          <svg className="w-5 h-5 text-[var(--color-accent)]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg> How to Use This Calculator
        </h2>
        <ol className="list-decimal ml-5 space-y-3 text-[#6B7280] text-sm leading-relaxed">
              <li><strong>Adjust the inputs:</strong> Use the sliders or text boxes to enter your specific financial numbers.</li>
              <li><strong>Review the charts:</strong> The interactive charts will update immediately, showing a visual breakdown of your investments and returns.</li>
              <li><strong>Analyze the results:</strong> Look at the summary cards and tables to understand your total invested amount, estimated returns, and final corpus.</li>
        </ol>
      </div>

    </>
  );
}

