"use client";

import React, { useState, useMemo } from 'react';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import { Line } from 'react-chartjs-2';
import InputSlider from '@/components/InputSlider';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

export default function FdVsSipPage() {
  const [monthlyInvestment, setMonthlyInvestment] = useState(5000);
  const [years, setYears] = useState(10);
  const [fdRate, setFdRate] = useState(7);
  const [sipRate, setSipRate] = useState(12);

  const calculateFutureValue = (monthly, rate, years) => {
    const months = years * 12;
    const monthlyRate = rate / 100 / 12;
    if (monthlyRate === 0) return monthly * months;
    return monthly * ((Math.pow(1 + monthlyRate, months) - 1) / monthlyRate) * (1 + monthlyRate);
  };

  const { fdTotal, sipTotal, totalInvested, chartData } = useMemo(() => {
    const fd = calculateFutureValue(monthlyInvestment, fdRate, years);
    const sip = calculateFutureValue(monthlyInvestment, sipRate, years);
    const invested = monthlyInvestment * years * 12;

    const labels = [];
    const fdData = [];
    const sipData = [];

    for (let i = 0; i <= years; i++) {
      labels.push(`Year ${i}`);
      if (i === 0) {
        fdData.push(0);
        sipData.push(0);
      } else {
        fdData.push(calculateFutureValue(monthlyInvestment, fdRate, i));
        sipData.push(calculateFutureValue(monthlyInvestment, sipRate, i));
      }
    }

    return {
      fdTotal: fd,
      sipTotal: sip,
      totalInvested: invested,
      chartData: {
        labels,
        datasets: [
          {
            label: 'SIP Value',
            data: sipData,
            borderColor: '#1B3A5C',
            backgroundColor: '#1B3A5C',
            borderWidth: 2,
            pointRadius: 0,
            pointHitRadius: 10,
            tension: 0.4,
          },
          {
            label: 'Savings Value',
            data: fdData,
            borderColor: '#C4993C',
            backgroundColor: '#C4993C',
            borderWidth: 2,
            pointRadius: 0,
            pointHitRadius: 10,
            tension: 0.4,
          },
        ],
      },
    };
  }, [monthlyInvestment, years, fdRate, sipRate]);

  const extraWealth = sipTotal - fdTotal;

  const formatCurrency = (value) =>
    new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0,
    }).format(value);

  const chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: 'top',
        labels: {
          color: '#1F2937',
          usePointStyle: true,
          boxWidth: 8,
        },
      },
      tooltip: {
        mode: 'index',
        intersect: false,
        callbacks: {
          label: (context) => {
            let label = context.dataset.label || '';
            if (label) {
              label += ': ';
            }
            if (context.parsed.y !== null) {
              label += formatCurrency(context.parsed.y);
            }
            return label;
          },
        },
      },
    },
    scales: {
      x: {
        grid: {
          display: false,
        },
        ticks: {
          color: '#6B7280',
          maxTicksLimit: 8,
        },
      },
      y: {
        grid: {
          color: 'rgba(27,58,92,0.05)',
        },
        ticks: {
          color: '#6B7280',
          callback: (value) => {
            if (value >= 1000000) return `$${(value / 1000000).toFixed(1)}M`;
            if (value >= 1000) return `$${(value / 1000).toFixed(1)}K`;
            return `$${value}`;
          },
        },
      },
    },
    interaction: {
      mode: 'nearest',
      axis: 'x',
      intersect: false,
    },
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="text-center mb-10">
        <h1 className="text-3xl md:text-4xl font-bold text-[#1F2937] mb-4">
          Savings vs SIP Calculator
        </h1>
        <p className="text-gray-500 max-w-2xl mx-auto">
          Compare the wealth generated by a traditional Savings Account versus an Equity SIP over time. See how compounding can work to your advantage.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Input Panel */}
        <div className="lg:col-span-5 space-y-6 glass-panel p-6 sm:p-8 rounded-2xl bg-[#f8f2ea]">
          <h2 className="text-xl font-bold text-[#1F2937] mb-6">Investment Details</h2>
          
          <InputSlider
            label="Monthly Investment"
            value={monthlyInvestment}
            min={500}
            max={100000}
            step={500}
            onChange={setMonthlyInvestment}
            prefix="$"
          />

          <InputSlider
            label="Investment Period"
            value={years}
            min={1}
            max={30}
            step={1}
            onChange={setYears}
            suffix=" Years"
          />

          <InputSlider
            label="Savings Interest Rate (p.a.)"
            value={fdRate}
            min={1}
            max={15}
            step={0.1}
            onChange={setFdRate}
            suffix="%"
          />

          <InputSlider
            label="SIP Expected Return (p.a.)"
            value={sipRate}
            min={1}
            max={30}
            step={0.1}
            onChange={setSipRate}
            suffix="%"
          />
        </div>

        {/* Results Panel */}
        <div className="lg:col-span-7 space-y-8">
          <div className="glass-panel p-6 sm:p-8 rounded-2xl bg-[#f8f2ea]">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-8">
              <div className="p-4 rounded-xl bg-white/50 border border-white">
                <p className="text-sm text-gray-500 mb-1">Total Invested</p>
                <p className="text-2xl font-bold text-[#1B3A5C]">
                  {formatCurrency(totalInvested)}
                </p>
              </div>
              <div className="p-4 rounded-xl bg-[#1B3A5C] text-white shadow-lg">
                <p className="text-sm text-white/80 mb-1">Extra Wealth via SIP</p>
                <p className="text-2xl font-bold text-white">
                  {formatCurrency(extraWealth)}
                </p>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-8">
              <div className="p-4 rounded-xl bg-white/50 border border-white">
                <p className="text-sm text-gray-500 mb-1 flex items-center gap-2">
                  <span className="w-3 h-3 rounded-full bg-[#C4993C]"></span>
                  Savings Total Value
                </p>
                <p className="text-2xl font-bold text-[#1F2937]">
                  {formatCurrency(fdTotal)}
                </p>
                <p className="text-sm text-[#059669] mt-1">
                  +{formatCurrency(fdTotal - totalInvested)} gains
                </p>
              </div>
              <div className="p-4 rounded-xl bg-white/50 border border-white">
                <p className="text-sm text-gray-500 mb-1 flex items-center gap-2">
                  <span className="w-3 h-3 rounded-full bg-[#1B3A5C]"></span>
                  SIP Total Value
                </p>
                <p className="text-2xl font-bold text-[#1F2937]">
                  {formatCurrency(sipTotal)}
                </p>
                <p className="text-sm text-[#059669] mt-1">
                  +{formatCurrency(sipTotal - totalInvested)} gains
                </p>
              </div>
            </div>

            <div className="h-[300px] w-full">
              <Line data={chartData} options={chartOptions} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

