"use client";
import CalculatorTabs from '@/components/CalculatorTabs';
import Link from 'next/link';
import { Landmark, BookOpen, Briefcase, LineChart, Clock, ArrowRight, Calculator, TrendingUp, Target, Layers, Wallet, Shield, BarChart3, Flame, GraduationCap, Home, Zap, Settings2, ArrowUpCircle, AlertTriangle, XCircle, Globe, PieChart } from 'lucide-react';
import Breadcrumb from '@/components/Breadcrumb';

const ARTICLES = [{
    href: '/blog/direct-vs-regular-mutual-fund',
    tag: 'Mutual Fund Guide',
    tagColor: 'text-[var(--color-accent)] bg-[var(--color-accent)]/10 border-[var(--color-accent)]/20',
    title: 'Direct vs Regular Mutual Fund: The 1% That Costs You Lakhs',
    excerpt: 'Both plans invest in the same portfolio. But the Regular plan silently eats 0.5-1.5% of your returns every year. Over 20 years, that costs you Rs 13+ Lakhs.',
    readTime: '7 min read',
    cta: 'Read Guide',
    icon: <TrendingUp className="w-5 h-5 text-[var(--color-accent)]" />,
    highlight: 'New',
    highlightColor: 'text-[var(--color-accent)]',
  },
  {
    href: '/blog/home-loan-with-low-cibil-score',
    tag: 'Home Loan Planning',
    tagColor: 'text-[var(--color-accent)] bg-[var(--color-accent)]/10 border-[var(--color-accent)]/20',
    title: 'How to Get a Home Loan with a Low CIBIL Score',
    excerpt: 'Having a low CIBIL score doesn\'t mean you can\'t buy a home. Learn the exact strategies to secure a home loan even with a score below 750.',
    readTime: '6 min read',
    cta: 'Read Guide',
    icon: <Home className="w-5 h-5 text-[var(--color-accent)]" />,
    highlight: 'New',
    highlightColor: 'text-[var(--color-accent)]',
  },
  {
    href: '/blog/why-net-worth-explodes-after-1-crore',
    tag: 'Wealth Building',
    tagColor: 'text-[var(--color-accent)] bg-[var(--color-accent)]/10 border-[var(--color-accent)]/20',
    title: 'Why the First 1 Crore is the Hardest (And Why Net Worth Explodes After)',
    excerpt: 'Discover the math and psychology behind why reaching your first 1 crore is the hardest part of investing, and how the power of compounding takes over afterward.',
    readTime: '5 min read',
    cta: 'Read Guide',
    icon: <TrendingUp className="w-5 h-5 text-[var(--color-accent)]" />,
    highlight: 'Trending',
    highlightColor: 'text-[var(--color-accent)]',
  },
  {
    href: '/blog/sip-vs-fd-ppf-rd',
    tag: 'Comparison Tool',
    tagColor: 'text-[#C4993C] bg-[rgba(196,153,60,0.1)] border-[rgba(196,153,60,0.25)]',
    title: 'SIP vs FD vs PPF Comparison Tool',
    excerpt:
      'Compare the wealth generated by Mutual Fund SIPs against traditional safe investments like PPF and Bank RDs. See exactly how much extra wealth you can generate.',
    readTime: '3 min read',
    cta: 'Try Tool',
    icon: <BarChart3 className="w-5 h-5 text-[#C4993C]" />,
    highlight: 'Interactive',
    highlightColor: 'text-[#C4993C]',
  },
  {
    href: '/tools/cost-of-delay-calculator',
    tag: 'Cost of Delay',
    tagColor: 'text-[var(--color-loss)] bg-[rgba(153,27,27,0.1)] border-[rgba(153,27,27,0.25)]',
    title: 'Cost of Delay Calculator — See What Waiting Costs You',
    excerpt:
      'Discover the devastating impact of delaying your SIP investments. See how much wealth you lose by waiting and find out exactly how much extra you\'ll need to invest to catch up.',
    readTime: '3 min read',
    cta: 'Try Calculator',
    icon: <Clock className="w-5 h-5 text-[var(--color-loss)]" />,
    highlight: 'Interactive',
    highlightColor: 'text-[var(--color-loss)]',
  },
  {
    href: '/tools/sip-based-on-salary',
    tag: 'SIP Planning',
    tagColor: 'text-[var(--color-accent)] bg-[rgba(27,58,92,0.12)] border-[rgba(27,58,92,0.25)]',
    title: 'How Much SIP Should I Do Based on My Salary?',
    excerpt:
      'Use the 50-30-20 budgeting rule to find your ideal SIP amount. Interactive calculator shows Conservative (10%), Moderate (20%), and Aggressive (30%) plans with 20-year projections.',
    readTime: '5 min read',
    cta: 'Try Calculator',
    icon: <Wallet className="w-5 h-5 text-[var(--color-accent)]" />,
    highlight: 'Interactive',
    highlightColor: 'text-[var(--color-accent)]',
  },
  {
    href: '/tools/retirement-sip-calculator',
    tag: 'Retirement',
    tagColor: 'text-[var(--color-accent)] bg-[rgba(27,58,92,0.1)] border-[rgba(27,58,92,0.25)]',
    title: 'How Much SIP Do I Need to Retire in India?',
    excerpt:
      'Enter your age, expenses, and retirement target — get the exact monthly SIP needed. See the devastating cost of delaying by just 5 years.',
    readTime: '6 min read',
    cta: 'Try Calculator',
    icon: <Shield className="w-5 h-5 text-[var(--color-accent)]" />,
    highlight: 'Interactive',
    highlightColor: 'text-[var(--color-accent)]',
  },
  {
    href: '/tools/sip-vs-lumpsum',
    tag: 'Comparison',
    tagColor: 'text-[var(--color-returns)] bg-[rgba(196,153,60,0.1)] border-[rgba(196,153,60,0.25)]',
    title: 'SIP vs Lump Sum — Which Is Better? Interactive Comparison',
    excerpt:
      'Compare SIP and Lumpsum returns under Bull, Bear, and Volatile market scenarios. See which strategy wins — and by how much — with real-time charts.',
    readTime: '5 min read',
    cta: 'Compare Now',
    icon: <BarChart3 className="w-5 h-5 text-[var(--color-returns)]" />,
    highlight: 'Interactive',
    highlightColor: 'text-[var(--color-returns)]',
  },
  {
    href: '/tools/sip-to-beat-inflation',
    tag: 'Inflation',
    tagColor: 'text-[var(--color-returns)] bg-[rgba(196,153,60,0.1)] border-[rgba(196,153,60,0.25)]',
    title: 'How Much SIP to Beat Inflation? Real vs Nominal Returns',
    excerpt:
      'See how inflation erodes your SIP returns. Dual-chart comparison of nominal vs real value, purchasing power erosion callout, and year-by-year breakdown.',
    readTime: '5 min read',
    cta: 'Try Calculator',
    icon: <Flame className="w-5 h-5 text-[var(--color-returns)]" />,
    highlight: 'Interactive',
    highlightColor: 'text-[var(--color-returns)]',
  },
  {
    href: '/tools/sip-to-reach-1-crore',
    tag: 'SIP Planning',
    tagColor: 'text-[var(--color-accent)] bg-[rgba(27,58,92,0.12)] border-[rgba(27,58,92,0.25)]',
    title: 'How Much SIP to Reach ₹1 Crore in 10, 15 & 20 Years?',
    excerpt:
      'Get the exact monthly SIP amount you need at 10%, 12%, and 15% annual returns across different time horizons. Includes step-up SIP comparison showing how you can start with 44% less.',
    readTime: '4 min read',
    cta: 'Read Guide',
    icon: <Calculator className="w-5 h-5 text-[var(--color-accent)]" />,
    highlight: '₹1 Crore Goal',
    highlightColor: 'text-[var(--color-accent)]',
  },
  {
    href: '/tools/sip-for-child-education',
    tag: 'Goal Planning',
    tagColor: 'text-[var(--color-accent)] bg-[rgba(27,58,92,0.10)] border-[rgba(27,58,92,0.25)]',
    title: 'SIP for Child Education — Education Goal Calculator India',
    excerpt:
      'Education inflation in India runs at 10%+ per year. Find exactly how much SIP you need to fund your child\'s engineering, medical, or MBA degree — before the cost doubles.',
    readTime: '5 min read',
    cta: 'Try Calculator',
    icon: <GraduationCap className="w-5 h-5 text-[var(--color-accent)]" />,
    highlight: 'Interactive',
    highlightColor: 'text-[var(--color-accent)]',
  },
  {
    href: '/tools/sip-for-house-down-payment',
    tag: 'Goal Planning',
    tagColor: 'text-[var(--color-accent)] bg-[rgba(27,58,92,0.10)] border-[rgba(27,58,92,0.25)]',
    title: 'SIP for House Down Payment — Save for Your Dream Home',
    excerpt:
      'Property prices rise 7%+ annually. See the future cost of that ₹80L flat, the down payment you need to save, and the exact monthly SIP to get there — with city-wise reference.',
    readTime: '5 min read',
    cta: 'Try Calculator',
    icon: <Home className="w-5 h-5 text-[var(--color-accent)]" />,
    highlight: 'Interactive',
    highlightColor: 'text-[var(--color-accent)]',
  },
  {
    href: '/tools/sip-during-market-crash',
    tag: 'Market Strategy',
    tagColor: 'text-[var(--color-loss)] bg-[rgba(153,27,27,0.1)] border-[rgba(153,27,27,0.25)]',
    title: 'SIP During Market Crash — Should You Stop or Continue?',
    excerpt:
      'Interactive crash simulator. See exactly how much wealth you lose by pausing SIP during a 40% market fall — and why rupee-cost averaging makes crashes the best time to invest.',
    readTime: '6 min read',
    cta: 'Run Simulation',
    icon: <Zap className="w-5 h-5 text-[var(--color-loss)]" />,
    highlight: 'Simulator',
    highlightColor: 'text-[var(--color-loss)]',
  },
  {
    href: '/blog/cagr-vs-xirr-vs-absolute-return',
    tag: 'Return Metrics',
    tagColor: 'text-[#C4993C] bg-[rgba(196,153,60,0.1)] border-[rgba(196,153,60,0.25)]',
    title: 'CAGR vs XIRR vs Absolute Return — What\'s the Difference?',
    excerpt:
      'When Groww shows "XIRR" and a fund shows "CAGR", are they the same? No — and the confusion costs investors bad decisions. This guide explains each clearly with worked examples.',
    readTime: '5 min read',
    cta: 'Read Guide',
    icon: <TrendingUp className="w-5 h-5 text-[var(--color-accent)]" />,
    highlight: 'CAGR vs XIRR',
    highlightColor: 'text-[#C4993C]',
  },
  {
    href: '/blog/swp-vs-sip',
    tag: 'Retirement Strategy',
    tagColor: 'text-[var(--color-returns)] bg-[rgba(5,150,105,0.1)] border-[rgba(5,150,105,0.25)]',
    title: 'SWP vs SIP: What\'s the Difference & Who Should Use Each?',
    excerpt: 'SIP builds your wealth over time, SWP pays you a monthly salary when you retire. Understand the core differences and tax advantages.',
    readTime: '4 min read',
    cta: 'Read Guide',
    icon: <Wallet className="w-5 h-5 text-[var(--color-returns)]" />,
    highlight: 'Trending',
    highlightColor: 'text-[var(--color-returns)]',
  },
  {
    href: '/blog/sip-vs-stp',
    tag: 'Lump Sum Strategy',
    tagColor: 'text-[#C4993C] bg-[rgba(196,153,60,0.1)] border-[rgba(196,153,60,0.25)]',
    title: 'SIP vs STP: How to Invest a Lump Sum Safely',
    excerpt: 'Got a huge bonus or sold a property? Learn how to use a Systematic Transfer Plan (STP) to avoid market timing risks.',
    readTime: '4 min read',
    cta: 'Read Guide',
    icon: <TrendingUp className="w-5 h-5 text-[#C4993C]" />,
  },
  {
    href: '/blog/flexi-sip',
    tag: 'Advanced SIP',
    tagColor: 'text-[var(--color-accent)] bg-[rgba(27,58,92,0.12)] border-[rgba(27,58,92,0.25)]',
    title: 'What is a Flexi SIP? (And Who Should Use It)',
    excerpt: 'Freelancer with irregular income? Learn how Flexi SIPs allow you to change your monthly investment amount without breaking discipline.',
    readTime: '3 min read',
    cta: 'Read Guide',
    icon: <Settings2 className="w-5 h-5 text-[var(--color-accent)]" />,
  },
  {
    href: '/blog/step-up-sip',
    tag: 'Wealth Multiplier',
    tagColor: 'text-[var(--color-returns)] bg-[rgba(5,150,105,0.1)] border-[rgba(5,150,105,0.25)]',
    title: 'Step-Up SIP: The Secret to Retiring Early',
    excerpt: 'Also known as a Top-Up SIP, learn how increasing your SIP by just 10% every year can double your final retirement corpus.',
    readTime: '3 min read',
    cta: 'Read Guide',
    icon: <ArrowUpCircle className="w-5 h-5 text-[var(--color-returns)]" />,
  },
  {
    href: '/blog/trigger-sip',
    tag: 'Tactical Strategy',
    tagColor: 'text-[var(--color-loss)] bg-[rgba(153,27,27,0.1)] border-[rgba(153,27,27,0.25)]',
    title: 'Trigger SIP: How to Automatically Buy the Dip',
    excerpt: 'Want to invest more money only when the stock market crashes? A Trigger SIP allows you to set rules for when your money gets invested.',
    readTime: '4 min read',
    cta: 'Read Guide',
    icon: <Zap className="w-5 h-5 text-[var(--color-loss)]" />,
  },
  {
    href: '/blog/dynamic-sip',
    tag: 'Smart Investing',
    tagColor: 'text-[var(--color-accent)] bg-[rgba(27,58,92,0.12)] border-[rgba(27,58,92,0.25)]',
    title: 'Dynamic SIP (Market-Linked SIP)',
    excerpt: 'Dynamic SIP takes the emotion out of investing by using algorithms to decide exactly how much you should invest this month based on valuations.',
    readTime: '4 min read',
    cta: 'Read Guide',
    icon: <TrendingUp className="w-5 h-5 text-[var(--color-accent)]" />,
  },
  {
    href: '/blog/common-sip-mistakes',
    tag: 'Mistakes to Avoid',
    tagColor: 'text-[var(--color-loss)] bg-[rgba(153,27,27,0.1)] border-[rgba(153,27,27,0.25)]',
    title: '7 Common SIP Mistakes to Avoid',
    excerpt: 'Are you unknowingly destroying your long-term wealth? Avoid these frequent mutual fund SIP mistakes like pausing during a crash.',
    readTime: '5 min read',
    cta: 'Read Guide',
    icon: <AlertTriangle className="w-5 h-5 text-[var(--color-loss)]" />,
    highlight: 'Must Read',
    highlightColor: 'text-[var(--color-loss)]',
  },
  {
    href: '/blog/types-of-sip',
    tag: 'Beginner Guide',
    tagColor: 'text-[#C4993C] bg-[rgba(196,153,60,0.1)] border-[rgba(196,153,60,0.25)]',
    title: '5 Types of SIPs Explained: Regular, Flexi, Perpetual',
    excerpt: 'Not all SIPs are created equal. Depending on your income stability and strategy, choose a SIP that fits your unique needs.',
    readTime: '3 min read',
    cta: 'Read Guide',
    icon: <Layers className="w-5 h-5 text-[#C4993C]" />,
  },
  {
    href: '/blog/sip-for-nris',
    tag: 'NRI Guide',
    tagColor: 'text-[var(--color-accent)] bg-[rgba(27,58,92,0.12)] border-[rgba(27,58,92,0.25)]',
    title: 'SIP for NRIs: A Complete Investing Guide',
    excerpt: 'Can NRIs invest in Indian Mutual Funds? Learn the FEMA rules, NRE/NRO accounts, and taxation for NRIs investing in India.',
    readTime: '4 min read',
    cta: 'Read Guide',
    icon: <Globe className="w-5 h-5 text-[var(--color-accent)]" />,
  },
  {
    href: '/blog/sip-vs-ulip',
    tag: 'Insurance vs Investment',
    tagColor: 'text-[var(--color-returns)] bg-[rgba(5,150,105,0.1)] border-[rgba(5,150,105,0.25)]',
    title: 'SIP vs ULIP: Why Mutual Funds Beat Insurance',
    excerpt: 'Never mix insurance and investment. See why pure mutual fund SIPs easily beat ULIPs over the long term.',
    readTime: '4 min read',
    cta: 'Read Guide',
    icon: <Shield className="w-5 h-5 text-[var(--color-returns)]" />,
  },
  {
    href: '/blog/what-is-expense-ratio',
    tag: 'Hidden Fees',
    tagColor: 'text-[#991B1B] bg-[#991B1B]/10 border-[#991B1B]/20',
    title: 'What is Expense Ratio? How 1% Costs You Lakhs',
    excerpt: 'Understand how mutual funds deduct expenses daily from your NAV, and why switching to Direct plans is the easiest way to save money.',
    readTime: '6 min read',
    cta: 'Read Guide',
    icon: <AlertTriangle className="w-5 h-5 text-[#991B1B]" />,
    highlight: 'Essential',
    highlightColor: 'text-[#991B1B]',
  },
  {
    href: '/blog/when-to-exit-mutual-fund',
    tag: 'Exit Strategy',
    tagColor: 'text-[#C4993C] bg-[#C4993C]/10 border-[#C4993C]/20',
    title: 'When Should You Exit a Mutual Fund?',
    excerpt: 'Don\'t panic sell during a market crash. Learn the 4 logical reasons to redeem your mutual funds, including goal achievement and consistent underperformance.',
    readTime: '7 min read',
    cta: 'Read Guide',
    icon: <Settings2 className="w-5 h-5 text-[#C4993C]" />,
    highlight: 'Strategy',
    highlightColor: 'text-[#C4993C]',
  },
  {
    href: '/blog/how-to-build-mutual-fund-portfolio',
    tag: 'Portfolio Strategy',
    tagColor: 'text-[#059669] bg-[#059669]/10 border-[#059669]/20',
    title: 'How to Build a Mutual Fund Portfolio (Core & Satellite)',
    excerpt: 'Stop buying 15 different mutual funds. Learn the Core and Satellite strategy to build a robust portfolio with just 4 funds while avoiding overlap.',
    readTime: '9 min read',
    cta: 'Read Guide',
    icon: <PieChart className="w-5 h-5 text-[#059669]" />,
    highlight: 'Trending',
    highlightColor: 'text-[#059669]',
  },
  {
    href: '/blog/large-cap-vs-mid-cap-vs-small-cap',
    tag: 'Fund Selection',
    tagColor: 'text-[#1B3A5C] bg-[#1B3A5C]/10 border-[#1B3A5C]/20',
    title: 'Large Cap vs Mid Cap vs Small Cap: Where to Invest?',
    excerpt: 'SEBI classifies stocks into 3 categories. Learn the risk-reward ratio of each, their historical drawdowns, and how to allocate based on your age.',
    readTime: '8 min read',
    cta: 'Read Guide',
    icon: <Layers className="w-5 h-5 text-[#1B3A5C]" />,
    highlight: 'New',
    highlightColor: 'text-[#1B3A5C]',
  },
  {
    href: '/blog/mutual-fund-taxation-guide',
    tag: 'Tax Guide 2026',
    tagColor: 'text-[#991B1B] bg-[#991B1B]/10 border-[#991B1B]/20',
    title: 'Mutual Fund Taxation in India (2026 Rules)',
    excerpt: 'Understand the new 20% STCG and 12.5% LTCG rates for equity funds, and how debt funds are taxed at slab rates without indexation benefits.',
    readTime: '8 min read',
    cta: 'Read Guide',
    icon: <Wallet className="w-5 h-5 text-[#991B1B]" />,
    highlight: 'Trending',
    highlightColor: 'text-[#991B1B]',
  },
  {
    href: '/blog/elss-vs-ppf-vs-nps',
    tag: 'Tax Saving 80C',
    tagColor: 'text-[#059669] bg-[#059669]/10 border-[#059669]/20',
    title: 'ELSS vs PPF vs NPS: Where to Invest for Section 80C?',
    excerpt: 'Compare lock-in periods, historical returns, and taxation at maturity (EEE vs EET) to choose the best tax-saving instrument for your goals.',
    readTime: '7 min read',
    cta: 'Read Guide',
    icon: <Target className="w-5 h-5 text-[#059669]" />,
    highlight: 'New',
    highlightColor: 'text-[#059669]',
  },
  {
    href: '/blog/index-fund-vs-active-fund',
    tag: 'Strategy Guide',
    tagColor: 'text-[#C4993C] bg-[#C4993C]/10 border-[#C4993C]/20',
    title: 'Index Fund vs Active Fund: Does NIFTY 50 Beat the Experts?',
    excerpt: 'SPIVA data shows 85%+ of Indian large-cap active funds fail to beat the index. Learn when to use index funds and when to trust an active manager.',
    readTime: '9 min read',
    cta: 'Read Guide',
    icon: <BarChart3 className="w-5 h-5 text-[#C4993C]" />,
    highlight: 'Deep Dive',
    highlightColor: 'text-[#C4993C]',
  },
  {
    href: '/blog/ai-trading-bots-vs-sip',
    tag: 'AI & Finance',
    tagColor: 'text-[#991B1B] bg-[#991B1B]/10 border-[#991B1B]/20',
    title: 'AI Trading Bots vs SIP Compounding: The Math Behind the Hype',
    excerpt: 'Can AI predict the stock market? Discover why complex algorithmic trading often loses to the boring, tax-free compounding of a Nifty 50 SIP.',
    readTime: '8 min read',
    cta: 'Read Guide',
    icon: <Settings2 className="w-5 h-5 text-[#991B1B]" />,
    highlight: 'New',
    highlightColor: 'text-[#991B1B]',
  },
  {
    href: '/blog/prepay-home-loan-vs-sip',
    tag: 'Real Estate',
    tagColor: 'text-[#1B3A5C] bg-[#1B3A5C]/10 border-[#1B3A5C]/20',
    title: 'Prepaying Home Loan vs Step-Up SIP: The Mathematical Truth',
    excerpt: 'Should you use extra cash to clear your 9% mortgage or invest it in a 12% equity SIP? We break down the math and tax implications.',
    readTime: '8 min read',
    cta: 'Read Guide',
    icon: <Home className="w-5 h-5 text-[#1B3A5C]" />,
    highlight: 'New',
    highlightColor: 'text-[#1B3A5C]',
  },
  {
    href: '/blog/car-loan-emi-vs-sip',
    tag: 'Opportunity Cost',
    tagColor: 'text-[#991B1B] bg-[#991B1B]/10 border-[#991B1B]/20',
    title: 'Car Loan EMI vs SIP: The Hidden Cost of Buying a Car',
    excerpt: 'See what happens to your retirement corpus when you invest ₹15,000/month instead of paying it toward a depreciating asset.',
    readTime: '7 min read',
    cta: 'Read Guide',
    icon: <AlertTriangle className="w-5 h-5 text-[#991B1B]" />,
    highlight: 'Trending',
    highlightColor: 'text-[#991B1B]',
  },
  {
    href: '/blog/sip-at-all-time-highs',
    tag: 'Market Timing',
    tagColor: 'text-[#C4993C] bg-[#C4993C]/10 border-[#C4993C]/20',
    title: 'Starting a SIP at Nifty All-Time Highs vs Waiting for a Crash',
    excerpt: 'Historical data reveals why trying to time the market usually results in lost returns, and why SIPs thrive at market peaks.',
    readTime: '6 min read',
    cta: 'Read Guide',
    icon: <TrendingUp className="w-5 h-5 text-[#C4993C]" />,
  },
  {
    href: '/blog/step-up-sip-for-late-starters',
    tag: 'Retirement Strategy',
    tagColor: 'text-[#059669] bg-[#059669]/10 border-[#059669]/20',
    title: 'Step-Up SIP vs Regular SIP for Late Starters (Age 35+)',
    excerpt: 'Starting late? Discover how increasing your SIP by just 10% every year can mathematically bridge the 10-year gap you missed.',
    readTime: '7 min read',
    cta: 'Read Guide',
    icon: <ArrowUpCircle className="w-5 h-5 text-[#059669]" />,
    highlight: 'Essential',
    highlightColor: 'text-[#059669]',
  },
  {
    href: '/blog/gold-sgb-vs-nifty-50-sip',
    tag: 'Inflation Hedges',
    tagColor: 'text-[#C4993C] bg-[#C4993C]/10 border-[#C4993C]/20',
    title: 'Sovereign Gold Bonds (SGB) vs Nifty 50 SIP: Which Beats Inflation?',
    excerpt: 'A side-by-side comparison of India\'s traditional safe haven against equity over a 15-year horizon, factoring in post-tax returns.',
    readTime: '8 min read',
    cta: 'Read Guide',
    icon: <Shield className="w-5 h-5 text-[#C4993C]" />,
  },
  {
    href: '/blog/step-up-sip-for-freelancers',
    tag: 'Gig Economy',
    tagColor: 'text-[#1B3A5C] bg-[#1B3A5C]/10 border-[#1B3A5C]/20',
    title: 'Step-Up SIP Strategy for Freelancers & Variable Income',
    excerpt: 'How to successfully build a massive retirement corpus using Step-Up SIPs even when your monthly income fluctuates wildly.',
    readTime: '8 min read',
    cta: 'Read Guide',
    icon: <Briefcase className="w-5 h-5 text-[#1B3A5C]" />,
    highlight: 'New',
    highlightColor: 'text-[#1B3A5C]',
  },
  {
    href: '/blog/investing-salary-hike-in-step-up-sip',
    tag: 'Career Growth',
    tagColor: 'text-[#059669] bg-[#059669]/10 border-[#059669]/20',
    title: 'How to Invest Your Annual Appraisal: The 50% Step-Up Rule',
    excerpt: 'Beat lifestyle creep mathematically. See what happens when you commit exactly 50% of your annual salary hike to your Step-Up SIP.',
    readTime: '7 min read',
    cta: 'Read Guide',
    icon: <TrendingUp className="w-5 h-5 text-[#059669]" />
  },
  {
    href: '/blog/step-up-sip-to-beat-education-inflation',
    tag: 'Goal Planning',
    tagColor: 'text-[#991B1B] bg-[#991B1B]/10 border-[#991B1B]/20',
    title: 'Using Step-Up SIP to Beat 12% Education Inflation in India',
    excerpt: 'A flat SIP will fail to fund your child\'s college degree. Learn how aggressive Step-Up SIPs bridge the 12% education inflation gap.',
    readTime: '9 min read',
    cta: 'Read Guide',
    icon: <GraduationCap className="w-5 h-5 text-[#991B1B]" />,
    highlight: 'Essential',
    highlightColor: 'text-[#991B1B]',
  },
  {
    href: '/blog/15-15-15-rule-mutual-funds-vs-step-up-sip',
    tag: 'Finance Rules',
    tagColor: 'text-[#C4993C] bg-[#C4993C]/10 border-[#C4993C]/20',
    title: 'The 15x15x15 Rule is Broken: Why You Need a Step-Up SIP',
    excerpt: 'We mathematically deconstruct India\'s most viral investing rule of thumb and prove why adding a 10% annual Step-Up crushes it.',
    readTime: '7 min read',
    cta: 'Read Guide',
    icon: <Calculator className="w-5 h-5 text-[#C4993C]" />
  },
  {
    href: '/blog/step-up-sip-vs-lumpsum-in-bull-market',
    tag: 'Market Strategy',
    tagColor: 'text-[#1B3A5C] bg-[#1B3A5C]/10 border-[#1B3A5C]/20',
    title: 'Step-Up SIP vs Lumpsum: What Works Best in a Bull Market?',
    excerpt: 'When markets are euphoric, should you deploy cash in a lump sum or use a highly aggressive Step-Up SIP? The data might surprise you.',
    readTime: '8 min read',
    cta: 'Read Guide',
    icon: <LineChart className="w-5 h-5 text-[#1B3A5C]" />
  },
  {
    href: '/blog/loan-against-mutual-funds-lamf',
    tag: 'Advanced Strategy',
    tagColor: 'text-[#1B3A5C] bg-[#1B3A5C]/10 border-[#1B3A5C]/20',
    title: 'Loan Against Mutual Funds (LAMF): The Billionaire Strategy',
    excerpt: 'Learn how the ultra-wealthy use the Buy, Borrow, Die strategy. Secure low-interest capital for emergencies without stopping your compounding.',
    readTime: '10 min read',
    cta: 'Read Guide',
    icon: <Landmark className="w-5 h-5 text-[#1B3A5C]" />,
    highlight: 'New',
    highlightColor: 'text-[#1B3A5C]',
  }
];

const CALCULATORS = [
  { href: '/',                        icon: <Calculator className="w-4 h-4 text-[var(--color-accent)]" />, label: 'Step-Up SIP Calculator',  desc: 'SIP with step-up, lump sum & inflation' },
  { href: '/lumpsum-calculator',       icon: <Layers     className="w-4 h-4 text-[var(--color-returns)]" />, label: 'Lumpsum Calculator',       desc: 'One-time investment future value'        },
  { href: '/target-amount-calculator', icon: <Target     className="w-4 h-4 text-[var(--color-accent)]"  />, label: 'SIP Goal Calculator',      desc: 'Time to reach ₹1 Crore'                 },
  { href: '/cagr-calculator',          icon: <TrendingUp className="w-4 h-4 text-[var(--color-accent)]" />, label: 'CAGR Calculator',          desc: 'Compound annual growth rate'             },
  { href: '/swp-calculator',           icon: <Wallet     className="w-4 h-4 text-[var(--color-accent)]" />, label: 'SWP Calculator',           desc: 'Monthly withdrawal planning'             },
  { href: '/cost-of-delay-calculator', icon: <Clock      className="w-4 h-4 text-[var(--color-loss)]" />, label: 'Cost of Delay Calculator', desc: 'See what waiting costs you'              },
  { href: '/tools/fd-vs-sip-calculator', icon: <TrendingUp className="w-4 h-4 text-[var(--color-accent)]" />, label: 'FD vs SIP Calculator', desc: 'Compare Fixed Deposit with SIP' },
  { href: '/tools/fire-calculator', icon: <Target className="w-4 h-4 text-[var(--color-accent)]" />, label: 'FIRE Calculator', desc: 'Early retirement planner' },
  { href: '/tools/xirr-calculator', icon: <TrendingUp className="w-4 h-4 text-[var(--color-accent)]" />, label: 'XIRR Calculator', desc: 'Calculate mutual fund XIRR' },
  { href: '/tools/nps-calculator', icon: <Wallet className="w-4 h-4 text-[var(--color-returns)]" />, label: 'NPS Calculator', desc: 'National Pension System planner' },
  { href: '/tools/ppf-calculator', icon: <Wallet className="w-4 h-4 text-[#C4993C]" />, label: 'PPF Calculator', desc: 'Public Provident Fund returns' },
  { href: '/tools/buy-vs-rent-calculator', icon: <Home className="w-4 h-4 text-[var(--color-accent)]" />, label: 'Buy vs Rent Calculator', desc: 'Real estate vs investing comparison' }
];


const TOOL_HREFS = [
  '/blog/sip-vs-fd-ppf-rd',
  '/tools/cost-of-delay-calculator',
  '/tools/sip-based-on-salary',
  '/tools/retirement-sip-calculator',
  '/tools/sip-vs-lumpsum',
  '/tools/sip-to-beat-inflation',
  '/tools/sip-during-market-crash',
  '/tools/sip-to-reach-1-crore',
  '/tools/sip-for-child-education',
  '/tools/sip-for-house-down-payment'
];

export default function BlogIndexPage() {
  const tools = ARTICLES.filter(a => TOOL_HREFS.includes(a.href));
  const guides = ARTICLES.filter(a => !TOOL_HREFS.includes(a.href));
  
  return (
    <main className="py-8 px-2 md:px-4 flex flex-col items-center">
      <div className="max-w-6xl w-full mx-auto space-y-8">

        <CalculatorTabs />
        <Breadcrumb items={[{ label: 'Guides' }]} />

        {/* Hero */}
        <div className="glass-panel p-7 relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-[rgba(27,58,92,0.1)] to-transparent pointer-events-none" />
          <div className="relative z-10 flex items-start gap-4">
            <div className="bg-[rgba(27,58,92,0.2)] border border-[var(--color-accent)] p-3 rounded-2xl flex-shrink-0">
              <BookOpen className="w-6 h-6 text-[var(--color-accent)]" />
            </div>
            <div>
              <h1 className="text-2xl md:text-3xl font-extrabold text-foreground mb-2">
                Investment Guides 
              </h1>
              <p className="text-gray-500 dark:text-gray-400 text-sm leading-relaxed max-w-xl">
                Free, jargon-free guides with interactive calculators for Indian investors — SIP planning,
                retirement, inflation, market scenarios, and more. Written by Rajat.
              </p>
            </div>
          </div>
        </div>

        {/* Articles */}
        <div className="w-full">
          <h2 className="text-xl font-bold text-foreground px-1 mb-4">All Guides</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 md:gap-6">
            {ARTICLES.map(({ href, tag, tagColor, title, excerpt, readTime, cta, icon, highlight, highlightColor }, index) => (
              <Link
                key={href}
                href={href}
                className="block glass-panel p-5 hover:bg-[rgba(27,58,92,0.02)] hover:border-[rgba(27,58,92,0.25)] border border-[#E8E4DF] transition-all group rounded-2xl h-full relative overflow-hidden"
              >
                {/* Corner Number Badge */}
                <div className="absolute top-0 left-0 bg-[var(--color-accent)] text-white text-[10px] font-bold px-3 py-1 rounded-br-xl z-20 shadow-sm">
                  #{index + 1}
                </div>
                
                <div className="flex flex-col h-full items-start gap-4 relative z-10 pt-1">
                  {/* Icon & Meta */}
                  <div className="flex w-full items-start justify-between">
                    <div className="bg-[rgba(0,0,0,0.03)] p-2.5 rounded-xl flex-shrink-0 group-hover:bg-[rgba(27,58,92,0.1)] transition-colors">
                      {icon}
                    </div>
                    <div className="flex flex-col items-end gap-1 text-right">
                      <span className={`text-[9px] font-semibold uppercase tracking-wider px-2 py-0.5 rounded-full border ${tagColor}`}>
                        {tag}
                      </span>
                      {highlight && (
                        <span className={`text-[10px] font-semibold ${highlightColor}`}>{highlight}</span>
                      )}
                    </div>
                  </div>

                  <div className="flex-1 flex flex-col w-full min-w-0">
                    <div className="flex items-center gap-1 mb-2 text-gray-500 dark:text-gray-400 text-[10px]">
                      <Clock className="w-3 h-3" />{readTime}
                    </div>

                    {/* Title */}
                    <h2 className="text-foreground font-bold text-base leading-snug mb-2 group-hover:text-[var(--color-accent)] transition-colors">
                      {title}
                    </h2>

                    {/* Excerpt */}
                    <p className="text-gray-500 dark:text-gray-400 text-sm leading-relaxed line-clamp-3 mb-4">
                      {excerpt}
                    </p>

                    {/* CTA */}
                    <div className="mt-auto pt-4 border-t border-gray-100">
                      <span className="inline-flex items-center gap-1.5 text-[var(--color-accent)] text-xs font-semibold group-hover:gap-2.5 transition-all">
                        {cta} <ArrowRight className="w-3.5 h-3.5" />
                      </span>
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>

        {/* Divider */}
        <div className="flex items-center gap-3">
          <div className="flex-1 h-px bg-black/5" />
          <span className="text-gray-600 dark:text-gray-400 text-xs">Free Calculators</span>
          <div className="flex-1 h-px bg-black/5" />
        </div>

        {/* Calculator cards */}
        <div>
          <h2 className="text-lg font-bold text-foreground mb-3 px-1">Try Our Free Calculators</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {CALCULATORS.map(({ href, icon, label, desc }) => (
              <Link
                key={href}
                href={href}
                className="flex items-center gap-3 glass-panel p-4 hover:bg-[rgba(27,58,92,0.08)] hover:border-[rgba(27,58,92,0.2)] border border-[#E8E4DF] transition-all group rounded-xl"
              >
                <div className="bg-[rgba(0,0,0,0.03)] p-2 rounded-lg flex-shrink-0 group-hover:bg-[rgba(27,58,92,0.15)] transition-colors">
                  {icon}
                </div>
                <div className="flex-1">
                  <p className="text-foreground font-semibold text-sm group-hover:text-[var(--color-accent)] transition-colors">{label}</p>
                  <p className="text-gray-500 dark:text-gray-400 text-xs">{desc}</p>
                </div>
                <ArrowRight className="w-4 h-4 text-gray-600 dark:text-gray-400 group-hover:text-[var(--color-accent)] transition-colors flex-shrink-0" />
              </Link>
            ))}
          </div>
        </div>

      </div>
    </main>
  );
}
