"use client";

import React, { useState } from 'react';
import Link from 'next/link';
import { ChevronDown, BarChart2, TrendingUp, AlertTriangle, ShieldCheck } from 'lucide-react';

export default function IndexVsActiveUS() {
  const [openFaq, setOpenFaq] = useState(null);

  const toggleFaq = (index) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  const faqData = [
    {
      question: "Are S&P 500 index funds entirely risk-free?",
      answer: "No. S&P 500 index funds are subject to broader market risks. If the US stock market drops by 20% in a bear market, an S&P 500 index fund will also drop by roughly 20%. However, they eliminate the specific 'manager risk' associated with a Wall Street fund manager picking the wrong stocks."
    },
    {
      question: "Why do actively managed mutual funds have such high fees?",
      answer: "Actively managed funds charge higher expense ratios (often 0.75% to 1.50%) to compensate the portfolio management team, cover extensive Wall Street research analysts' salaries, and handle the higher transaction costs generated by frequently buying and selling stocks."
    },
    {
      question: "What was Warren Buffett&apos;s million-dollar bet?",
      answer: "In 2007, Warren Buffett made a $1 million bet that an unmanaged, low-cost S&P 500 index fund would outperform a basket of high-fee hedge funds over a 10-year period. Buffett won the bet decisively, proving that after fees are deducted, active management rarely beats the broader market."
    },
    {
      question: "Do active funds ever beat the market?",
      answer: "Yes, some active funds do beat the market in any given year. The problem is consistency. Studies like the SPIVA US Scorecard show that over 10 to 15-year periods, more than 85% to 90% of actively managed US large-cap funds fail to outperform the S&P 500."
    },
    {
      question: "Which one should I choose for my 401(k) or Roth IRA?",
      answer: "For long-term retirement accounts like a 401(k) or Roth IRA, low-cost index funds (like an S&P 500 or Total Stock Market index fund) are widely considered the superior choice due to their rock-bottom fees and historically reliable compounded growth."
    }
  ];

  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": faqData.map((faq) => ({
      "@type": "Question",
      "name": faq.question,
      "acceptedAnswer": {
        "@type": "Answer",
        "text": faq.answer,
      },
    })),
  };

  return (
    <main className="min-h-screen bg-[var(--background)] py-10">
      <div className="max-w-6xl w-full mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Breadcrumb (Visual) */}
        <nav className="text-sm mb-6 text-gray-500 dark:text-gray-400">
          <Link href="/us" className="hover:text-foreground">Home</Link> &gt;{' '}
          <Link href="/us/blog" className="hover:text-foreground">Blog</Link> &gt;{' '}
          <span className="text-foreground font-medium">Index Funds vs Actively Managed Funds</span>
        </nav>

        {/* Header Section */}
        <header className="mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-6 leading-tight">
            S&P 500 Index Funds vs Active Mutual Funds: The Ultimate Guide
          </h1>
          <p className="text-lg text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
            When setting up a 401(k), a Roth IRA, or a standard brokerage account, millions of Americans face the exact same question: Should I invest in a simple S&P 500 Index Fund, or should I pay a Wall Street professional to actively manage my money? For decades, active management was the standard on Wall Street. But thanks to pioneers like John Bogle and Vanguard, passive index investing has revolutionized wealth building.
          </p>
          <p className="text-lg text-gray-600 dark:text-gray-300 leading-relaxed">
            In this comprehensive, data-driven 2000-word guide, we strip away the financial jargon to expose the real differences between active and passive investing. From the devastating impact of fee drag on your retirement corpus to Warren Buffett&apos;s famous million-dollar wager, we will give you the exact framework you need to make the right choice for your financial future.
          </p>
        </header>

        {/* Content Block 1 */}
        <section className="glass-panel p-6 sm:p-8 rounded-3xl mb-12">
          <h2 className="text-2xl font-bold text-foreground mb-6 flex items-center gap-3">
            <TrendingUp className="text-[#059669] w-7 h-7" />
            What is an Actively Managed Mutual Fund?
          </h2>
          <div className="space-y-4 text-gray-700 dark:text-gray-300 leading-relaxed">
            <p>
              An actively managed mutual fund is a pool of money overseen by professional fund managers and an army of Wall Street research analysts. Their core objective is to outperform a specific market benchmark (like the S&P 500) and generate <strong>Alpha</strong> (excess returns above the market average).
            </p>
            <p>
              To achieve this, managers actively buy and sell stocks based on complex financial models, economic forecasting, and market timing. If they believe the tech sector is overvalued, they might dump their shares of Apple or Microsoft. If they think healthcare is poised for a breakout, they will heavily overweight companies like Johnson & Johnson.
            </p>
            <h3 className="text-xl font-semibold text-foreground mt-6 mb-3">The Illusion of Superiority</h3>
            <p>
              The sales pitch for active funds is compelling: &quot;Why settle for average market returns when you can hire an expert to beat the market?&quot; However, this expertise comes at a steep price. Active funds charge a significantly higher <strong>Expense Ratio</strong> to pay for those high Wall Street salaries, trading commissions, and marketing budgets.
            </p>
            <p>
              In the United States, equity active funds frequently charge anywhere from 0.75% to over 1.50% annually. Over a 30-year investing horizon, these fees act as an anchor, aggressively dragging down the magic of compound interest. Furthermore, data consistently shows that the majority of these highly paid experts actually <em>underperform</em> the basic market indices over long periods.
            </p>
          </div>
        </section>

        {/* Content Block 2 */}
        <section className="glass-panel p-6 sm:p-8 rounded-3xl mb-12">
          <h2 className="text-2xl font-bold text-foreground mb-6 flex items-center gap-3">
            <BarChart2 className="text-[var(--color-accent)] w-7 h-7" />
            What is an Index Fund (Passive Investing)?
          </h2>
          <div className="space-y-4 text-gray-700 dark:text-gray-300 leading-relaxed">
            <p>
              An Index Fund operates on a completely different ideology, famously summarized by Vanguard founder John Bogle: <em>&quot;Don&apos;t look for the needle in the haystack. Just buy the haystack!&quot;</em> Instead of trying to guess which stocks will go up, an index fund simply buys all the stocks in a given index (like the 500 largest US companies in the S&P 500) and holds them in the exact same proportion.
            </p>
            <p>
              If Amazon makes up 4% of the S&P 500, an S&P 500 index fund allocates exactly 4% of its cash to Amazon. There is no guessing, no market timing, and no high-priced managers making emotional decisions. The fund simply runs on algorithmic autopilot.
            </p>
            <h3 className="text-xl font-semibold text-foreground mt-6 mb-3">The Power of Low Fees</h3>
            <p>
              Because there is no active stock picking involved, the operating costs of index funds are extraordinarily low. Today, you can buy top-tier S&P 500 index funds or ETFs (like VOO or FXAIX) with expense ratios as low as <strong>0.03%</strong>. Some brokerages even offer zero-fee index funds.
            </p>
            <p>
              By capturing the exact return of the market and paying virtually zero fees, index funds ensure that almost 100% of the market's historical upward compounding ends up exactly where it belongs: in your retirement account.
            </p>
          </div>
        </section>

        {/* The Fee Drag Example */}
        <section className="glass-panel p-6 sm:p-8 rounded-3xl mb-12 bg-opacity-40 dark:bg-opacity-10 border-l-4 border-l-[var(--color-accent)]">
          <h2 className="text-2xl font-bold text-foreground mb-4">The Mathematical Reality: The Devastating Fee Drag</h2>
          <p className="text-gray-700 dark:text-gray-300 mb-6 leading-relaxed">
            To truly understand the difference, let us look at the mathematics of fee drag inside a typical 401(k). Assume you invest $500 a month for 30 years. Both the Active Fund and the Index Fund manage to generate a gross return of 10% annually before fees.
          </p>
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-gray-200 dark:border-gray-700">
                  <th className="py-3 px-4 text-foreground font-semibold">Factor</th>
                  <th className="py-3 px-4 text-foreground font-semibold">Active Fund</th>
                  <th className="py-3 px-4 text-foreground font-semibold">Index Fund</th>
                </tr>
              </thead>
              <tbody className="text-gray-700 dark:text-gray-300">
                <tr className="border-b border-gray-200 dark:border-gray-700 bg-white/50 dark:bg-black/20">
                  <td className="py-3 px-4">Expense Ratio</td>
                  <td className="py-3 px-4 text-[#991B1B] font-medium">1.25%</td>
                  <td className="py-3 px-4 text-[#059669] font-medium">0.05%</td>
                </tr>
                <tr className="border-b border-gray-200 dark:border-gray-700">
                  <td className="py-3 px-4">Net Annual Return</td>
                  <td className="py-3 px-4">8.75%</td>
                  <td className="py-3 px-4">9.95%</td>
                </tr>
                <tr className="bg-white/50 dark:bg-black/20 font-bold">
                  <td className="py-3 px-4">Final Corpus (After 30 Yrs)</td>
                  <td className="py-3 px-4 text-foreground">$848,000</td>
                  <td className="py-3 px-4 text-[#059669]">$1,072,000</td>
                </tr>
              </tbody>
            </table>
          </div>
          <p className="mt-4 text-sm text-gray-600 dark:text-gray-400">
            <strong>Insight:</strong> For doing absolutely nothing except charging a higher management fee, the active fund siphoned over $224,000 of your potential wealth. This is the tragic reality of Wall Street fees.
          </p>
        </section>

        {/* Warren Buffett Bet */}
        <section className="glass-panel p-6 sm:p-8 rounded-3xl mb-12">
          <h2 className="text-2xl font-bold text-foreground mb-6 flex items-center gap-3">
            <AlertTriangle className="text-[#991B1B] w-7 h-7" />
            Warren Buffett&apos;s Million-Dollar Bet
          </h2>
          <div className="space-y-4 text-gray-700 dark:text-gray-300 leading-relaxed">
            <p>
              If active managers are so smart, surely they beat the market? To settle this debate, legendary investor Warren Buffett issued a famous challenge in 2007. He bet $1 million that an unmanaged, low-cost S&P 500 index fund would beat a basket of elite hedge funds over a 10-year period.
            </p>
            <p>
              Protégé Partners accepted the bet and selected five "fund of funds" containing hundreds of top-tier active hedge funds. Over the next decade, which included the 2008 financial crisis and the subsequent bull run, the results were staggering.
            </p>
            <p>
              Buffett&apos;s chosen S&P 500 index fund compounded at 7.1% annually. The active hedge funds managed a dismal 2.2% annual return. The hedge fund managers didn't necessarily pick bad stocks, but their astronomical fees (often &quot;2 and 20&quot; - 2% management fee plus 20% of profits) completely destroyed the returns passed on to investors. Buffett decisively won the bet, proving that high fees are the enemy of the long-term investor.
            </p>
            <p>
              The definitive data backs Buffett up. The <strong>SPIVA (S&P Indices Versus Active) US Scorecard</strong> repeatedly shows that over a 15-year horizon, more than 90% of actively managed US large-cap mutual funds fail to beat the S&P 500.
            </p>
          </div>
        </section>

        
        {/* Tax Efficiency Block */}
        <section className="glass-panel p-6 sm:p-8 rounded-3xl mb-12">
          <h2 className="text-2xl font-bold text-foreground mb-6 flex items-center gap-3">
            <TrendingUp className="text-[#059669] w-7 h-7" />
            The Hidden Advantage: Tax Efficiency in Taxable Accounts
          </h2>
          <div className="space-y-4 text-gray-700 dark:text-gray-300 leading-relaxed">
            <p>
              While fee drag gets the most attention, there is a second silent killer of wealth in active mutual funds: <strong>Taxes</strong>. If you hold an active mutual fund in a standard taxable brokerage account (outside of a tax-advantaged 401(k) or IRA), you will face significant tax headwinds.
            </p>
            <p>
              Active fund managers are constantly buying and selling stocks to try and beat the market. This high <em>portfolio turnover</em> generates short-term and long-term capital gains. By law, mutual funds must distribute these capital gains to their shareholders at the end of the year. 
            </p>
            <p>
              This means you could be hit with a massive capital gains tax bill for the year, even if you never sold a single share of the mutual fund itself! You are effectively being taxed on the manager&apos;s trading activity. 
            </p>
            <p>
              Index funds, on the other hand, are incredibly tax-efficient. Because they only buy or sell stocks when the underlying index changes (which is rare), they have very low turnover (often 2% to 4%). As a result, they generate very few capital gains distributions, allowing your money to compound tax-deferred until you decide to sell your shares.
            </p>
            <h3 className="text-xl font-semibold text-foreground mt-6 mb-3">Building a 3-Fund Portfolio</h3>
            <p>
              If passive investing is so powerful, how should you structure your investments? The gold standard for modern index investors is the <strong>Bogleheads 3-Fund Portfolio</strong>. Instead of picking dozens of active funds, you can capture the entire global economy with just three low-cost index funds:
            </p>
            <ul className="list-disc pl-6 space-y-3">
              <li><strong>Total US Stock Market Index Fund:</strong> Covers large, mid, and small-cap US companies.</li>
              <li><strong>Total International Stock Index Fund:</strong> Provides exposure to developed and emerging global markets outside the US.</li>
              <li><strong>Total US Bond Market Index Fund:</strong> Adds stability, fixed income, and downside protection during stock market crashes.</li>
            </ul>
            <p>
              By allocating your capital across these three index funds, you achieve maximum diversification, minimum fees, and supreme tax efficiency. This setup requires almost zero maintenance beyond an annual rebalancing.
            </p>
          </div>
        </section>
  
        {/* Edge Cases Section */}
        <section className="glass-panel p-6 sm:p-8 rounded-3xl mb-12 border border-[var(--color-accent)]/20">
          <h2 className="text-2xl font-bold text-foreground mb-6 flex items-center gap-3">
            <ShieldCheck className="text-[var(--color-accent)] w-7 h-7" />
            Edge Cases: Are Active Funds Ever Worth It?
          </h2>
          <div className="space-y-4 text-gray-700 dark:text-gray-300 leading-relaxed">
            <p>
              With such damning evidence against active management, is there any reason to ever buy an active fund? Yes, but only in very specific, inefficient markets. The US Large-Cap market (the S&P 500) is highly efficient, meaning millions of computers analyze every piece of data instantly, making alpha impossible to find.
            </p>
            <ul className="list-disc pl-6 space-y-3">
              <li>
                <strong>Emerging Markets & International:</strong> Markets in developing nations are often less efficient. Information isn&apos;t as easily accessible. In these spaces, a skilled, &quot;boots on the ground&quot; fund manager can sometimes find mispriced assets and beat the index.
              </li>
              <li>
                <strong>Small-Cap Stocks:</strong> Similar to emerging markets, micro-cap and small-cap US companies receive much less analyst coverage than Apple or Nvidia. Active managers occasionally exploit these inefficiencies, though the gap is closing.
              </li>
              <li>
                <strong>Downside Protection:</strong> Pure index funds ride the market all the way up, but also all the way down. An active manager has the mandate to move to cash or bonds during a severe recession, potentially protecting your portfolio from massive drawdowns.
              </li>
            </ul>
          </div>
        </section>

        {/* Conclusion / Verdict */}
        <section className="glass-panel p-6 sm:p-8 rounded-3xl mb-12">
          <h2 className="text-2xl font-bold text-foreground mb-4">The Verdict: How to Build Your Portfolio</h2>
          <p className="text-gray-700 dark:text-gray-300 mb-4 leading-relaxed">
            For the vast majority of retail investors setting up a 401(k), IRA, or taxable brokerage account, the debate is settled. <strong>Low-cost Index Funds are the clear winner.</strong>
          </p>
          <ul className="list-disc pl-6 space-y-3 text-gray-700 dark:text-gray-300">
            <li><strong>The Core:</strong> Make broad market index funds (like an S&P 500 or Total US Stock Market fund) the absolute core of your portfolio. They provide instant diversification and minimal fee drag.</li>
            <li><strong>The Satellite:</strong> If you must use active funds, limit them to inefficient sectors like Emerging Markets, and never pay more than a 0.75% expense ratio.</li>
          </ul>
          <p className="mt-4 text-gray-700 dark:text-gray-300 font-medium">
            Remember, in investing, you get exactly what you <em>don&apos;t</em> pay for. Keep your costs rock bottom, automate your investments, and let the historical compounding of American business work for you.
          </p>
        </section>

        
        {/* Calculator CTA */}
        <section className="max-w-6xl w-full mx-auto mt-12 mb-12">
          <div className="glass-panel p-8 rounded-3xl bg-gradient-to-br from-[rgba(27,58,92,0.05)] to-transparent border border-[rgba(27,58,92,0.1)] flex flex-col md:flex-row items-center justify-between gap-6">
            <div>
              <h3 className="text-2xl font-bold text-foreground mb-2">Run the Numbers Yourself</h3>
              <p className="text-gray-600 dark:text-gray-400">
                Ready to see how compounding works in real life? Use our free calculators to project your wealth, account for inflation, and plan your goals.
              </p>
            </div>
            <div className="flex flex-col sm:flex-row gap-4 shrink-0">
              <Link href="/us/dca-calculator" className="px-6 py-3 bg-[var(--color-accent)] text-white font-semibold rounded-xl hover:bg-[#152e4d] transition-all shadow-md text-center">
                DCA Calculator
              </Link>
              <Link href="/us/lumpsum-calculator" className="px-6 py-3 bg-white dark:bg-gray-800 text-[var(--color-accent)] font-semibold rounded-xl border border-[var(--color-accent)] hover:bg-gray-50 transition-all text-center">
                Lumpsum Calculator
              </Link>
            </div>
          </div>
        </section>

        {/* FAQ Section */}
        <section className="max-w-6xl w-full mx-auto mt-12 mb-16">
          <h2 className="text-3xl font-bold text-foreground mb-8 text-center">Frequently Asked Questions</h2>
          <div className="space-y-4">
            {faqData.map((faq, index) => (
              <div key={index} className="glass-panel rounded-2xl overflow-hidden transition-all duration-300">
                <button 
                  onClick={() => toggleFaq(index)}
                  className="w-full px-6 py-5 flex items-center justify-between focus:outline-none"
                  aria-expanded={openFaq === index}
                >
                  <span className="text-left font-semibold text-foreground text-lg">{faq.question}</span>
                  <ChevronDown className={`w-5 h-5 text-gray-500 transition-transform duration-300 ${openFaq === index ? 'rotate-180' : ''}`} />
                </button>
                <div 
                  className={`px-6 overflow-hidden transition-all duration-300 ease-in-out ${
                    openFaq === index ? 'pb-5 max-h-[500px] opacity-100' : 'max-h-0 opacity-0'
                  }`}
                >
                  <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
                    {faq.answer}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* JSON-LD Schemas */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
        />
        
      </div>
    </main>
  );
}
